language: php
php:
- '7.0'
- '7.1'
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS v0lt;'
- mysql -e 'CREATE TABLE `v0lt`.`links` (`id` int(11) not null auto_increment, `short` varchar(10), `long` varchar(1000), `added` varchar(30), primary key(`id`)) engine=InnoDB default charset=latin1;'
script: phpunit tests.php