language: php
php:
- '7.0'
- '7.1'
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS v0lt;'
- curl -s http://getcomposer.org/installer | php
- php composer.phar install -n
- mkdir ~/coverage/
script: phpunit tests/tests.php --coverage-xml ~/coverage/ --whitelist /tests/
after_script:
- php vendor/bin/codacycoverage phpunit ~/coverage/